In [2]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.4)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd

In [4]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

In [5]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
movies=movies.merge(credits,on='title')

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
#genres
#id
#keywords
#title
#overview
#cast
#crew

movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [10]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies.duplicated().sum()

np.int64(0)

In [15]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action','Adventure','Fantacy',''SciFi]

In [17]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [18]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [19]:
movies['genres']=movies['genres'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies['keywords']=movies['keywords'].apply(convert)

In [22]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
        
    return L

In [23]:
movies['cast']=movies['cast'].apply(convert3)

movies.head()

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [26]:
movies['crew']=movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [28]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [29]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [33]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['crew']+movies['cast']

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
new_df=movies[['movie_id','title','tags']]

In [36]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [37]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\dell\AppData\Local\Temp\ipykernel_17304\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [39]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JamesCameron SamWorthington ZoeSaldana SigourneyWeaver'

In [40]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\dell\AppData\Local\Temp\ipykernel_17304\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [41]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d jamescameron samworthington zoesaldana sigourneyweaver'

In [42]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger goreverbinski johnnydepp orlandobloom keiraknightley"

In [43]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (2.2.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
##text vectorization -using count vectorization 
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [45]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [46]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [47]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [48]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [49]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [50]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [51]:
import nltk

In [52]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [53]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [54]:
['loved','loving','love']
ps.stem('loved')

'love'

In [55]:
ps.stem('loving')

'love'

In [56]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\dell\AppData\Local\Temp\ipykernel_17304\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [57]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
similarity=cosine_similarity(vectors)

In [60]:
similarity[0]

array([1.        , 0.08740748, 0.05827165, ..., 0.02418254, 0.02564946,
       0.        ], shape=(4806,))

In [61]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(539, np.float64(0.25038669783359574)),
 (1192, np.float64(0.24779731389167606)),
 (507, np.float64(0.24283093212859141)),
 (260, np.float64(0.2409900932515112)),
 (1214, np.float64(0.23939494881986934))]

In [62]:
sorted(similarity[0],reverse=True)

[np.float64(1.0000000000000002),
 np.float64(0.25038669783359574),
 np.float64(0.24779731389167606),
 np.float64(0.24283093212859141),
 np.float64(0.2409900932515112),
 np.float64(0.23939494881986934),
 np.float64(0.233785950059759),
 np.float64(0.23174488732966075),
 np.float64(0.23084512921915967),
 np.float64(0.23084512921915967),
 np.float64(0.2294157338705618),
 np.float64(0.21677749238103003),
 np.float64(0.21629522817435),
 np.float64(0.21526419295572297),
 np.float64(0.21486752129677),
 np.float64(0.21296183592613546),
 np.float64(0.21239769762143662),
 np.float64(0.21239769762143662),
 np.float64(0.2108663315950723),
 np.float64(0.20857039859669468),
 np.float64(0.20770324619863198),
 np.float64(0.20751433915982237),
 np.float64(0.20395079136182276),
 np.float64(0.20395079136182276),
 np.float64(0.2029530274475215),
 np.float64(0.2029530274475215),
 np.float64(0.2024645717996314),
 np.float64(0.19767387315371682),
 np.float64(0.19466570535691505),
 np.float64(0.19194297398747862),
 np.float64(0.19117977822546817),
 np.float64(0.19088542889273336),
 np.float64(0.19088542889273336),
 np.float64(0.18848425873126295),
 np.float64(0.18731716231633883),
 np.float64(0.18731716231633883),
 np.float64(0.18541926977182405),
 np.float64(0.1853959098637286),
 np.float64(0.1842105263157895),
 np.float64(0.18172434016970185),
 np.float64(0.1813690625275029),
 np.float64(0.1810898182317451),
 np.float64(0.18074256993863339),
 np.float64(0.18074256993863339),
 np.float64(0.17954621161490197),
 np.float64(0.17954621161490197),
 np.float64(0.177343107178349),
 np.float64(0.177343107178349),
 np.float64(0.17699808135119718),
 np.float64(0.17699808135119718),
 np.float64(0.17521916101261562),
 np.float64(0.1745025152241333),
 np.float64(0.17206180040292132),
 np.float64(0.16943474841747155),
 np.float64(0.1692777916923361),
 np.float64(0.1691275228729346),
 np.float64(0.16742770563222897),
 np.float64(0.16556654463313053),
 np.float64(0.16556654463313053),
 np.float64(0.16481712868606585),
 np.float64(0.16452254913212452),
 np.float64(0.16452254913212452),
 np.float64(0.16350382386265752),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076252),
 np.float64(0.16222142113076252),
 np.float64(0.15907119074394446),
 np.float64(0.15907119074394446),
 np.float64(0.15789473684210528),
 np.float64(0.15747244473304667),
 np.float64(0.15609763526361567),
 np.float64(0.15609763526361567),
 np.float64(0.15585730003983933),
 np.float64(0.15585730003983933),
 np.float64(0.15389675281277312),
 np.float64(0.15328483487124145),
 np.float64(0.152008377581442),
 np.float64(0.15061880828219448),
 np.float64(0.15018785229652765),
 np.float64(0.14910501299480672),
 np.float64(0.14808721943977307),
 np.float64(0.14808721943977307),
 np.float64(0.14673479641335554),
 np.float64(0.14673479641335554),
 np.float64(0.14567913668701626),
 np.float64(0.14567913668701626),
 np.float64(0.14509525002200235),
 np.float64(0.14509525002200233),
 np.float64(0.14509525002200233),
 np.float64(0.1442149876003076),
 np.float64(0.14350946197048198),
 np.float64(0.1433848336691011),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.1411956236812263),
 np.float64(0.1404878717372541),
 np.float64(0.13977653617040256),
 np.float64(0.1391037210186643),
 np.float64(0.1391037210186643),
 np.float64(0.1391037210186643),
 np.float64(0.13834289277321493),
 np.float64(0.13834289277321493),
 np.float64(0.13834289277321493),
 np.float64(0.13764944032233709),
 np.float64(0.13710212427677043),
 np.float64(0.13710212427677043),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13518451760896877),
 np.float64(0.13518451760896877),
 np.float64(0.13497638119975428),
 np.float64(0.13497638119975428),
 np.float64(0.13369695534647594),
 np.float64(0.13369695534647594),
 np.float64(0.13334518676566626),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13112201362143713),
 np.float64(0.1302565123238377),
 np.float64(0.130066495428618),
 np.float64(0.12988108336653278),
 np.float64(0.12988108336653278),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12892051277806202),
 np.float64(0.12824729401064427),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.126673647984535),
 np.float64(0.126673647984535),
 np.float64(0.12565617248750865),
 np.float64(0.12565617248750865),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12487810821089254),
 np.float64(0.12487810821089254),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699313),
 np.float64(0.12262786789699313),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12166606584807191),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.1204950466257556),
 np.float64(0.1204950466257556),
 np.float64(0.1204950466257556),
 np.float64(0.11980845957463077),
 np.float64(0.11959121830873498),
 np.float64(0.11959121830873498),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.116543309349613),
 np.float64(0.116543309349613),
 np.float64(0.11587244366483038),
 np.float64(0.11587244366483038),
 np.float64(0.11587244366483038),
 np.float64(0.1147078669352809),
 np.float64(0.1147078669352809),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.1139194873735864),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11239029738980326),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11037769642208699),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10743376064838502),
 np.float64(0.10743376064838502),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.10650358071057624),
 np.float64(0.10650358071057624),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10390486669322622),
 np.float64(0.10385162309931599),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.10301070542879115),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10203255357771539),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.1003911722115382),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09694584179118516),
 np.float64(0.0967301666813349),
 np.float64(0.09567297464698798),
 np.float64(0.09558988911273408),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09304036594559835),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09183979479633063),
 np.float64(0.09176629354822471),
 np.float64(0.09176629354822471),
 np.float64(0.09086217008485092),
 np.float64(0.09086217008485092),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09012301173931252),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.0891313035643173),
 np.float64(0.08903057122447033),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08646430798325933),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08520286456846099),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.0830812984794528),
 np.float64(0.0830812984794528),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303291),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08175191193132876),
 np.float64(0.08175191193132876),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08048436365855338),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.07987230638308718),
 np.float64(0.0792740035289418),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07768997059248714),
 np.float64(0.0770085628656519),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07664241743562072),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),

In [63]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)
        
    return

In [64]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [65]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Ender's Game
Aliens vs Predator: Requiem